// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require("Verifier");

contract("Verifier", (accounts) => {
  const owner = accounts[0];
  // - use the contents from proof.json generated from zokrates steps
  const proof = require("../../zokrates/code/square/proof.json");

  beforeEach(async function () {
    this.contract = await Verifier.new({ from: owner });
  });

  // Test verification with correct proof
  it("Test verification with correct proof", async function () {
    const {
      proof: { a, b, c },
      inputs: input,
    } = proof;

    let result = await this.contract.verifyTx.call(proof.proof, proof.inputs);
    assert.equal(result, true, "Test verification with correct proof");
  });

  // Test verification with incorrect proof
  it("Test verification with incorrect proof", async function () {
    let result = await this.contract.verifyTx.call(proof.proof, [0]);
    assert.equal(result, false, "Test verification with incorrect proof.");
  });
});
